language: node_js

node_js: --lts

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile

script: yarn test

after_script:
  - yarn global add codecov
  - codecov
