language: node_js

node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile

before_script: greenkeeper-lockfile-update

script:
  - set -e
  - yarn test
  - yarn build

after_script:
  - greenkeeper-lockfile-upload
  - yarn global add codecov
  - codecov -f coverage/*.json
